#!/bin/bash
source autobuild.conf
SCRIPTS_PATH=$SCRAPER_LOCATIONS/
URL=$(cat $(find $BUILD_SCRIPTS_ROOT/ -name $1) | grep URL= | sed 's![^/]*$!!' | sed 's/URL=//g' | sed 's/.$//' | sed 's![^/]*$!!' | sed 's/.$//g' | sed 's![^/]*$!!' )
PACKAGE_PREFIX=$(cat $(find $BUILD_SCRIPTS_ROOT/ -name $1) | grep URL | head -1 | sed 's/URL=//g'| sed -r 's|(.*)/||'| sed 's|.tar.*||g' | sed 's|-[^-]*$||g')
LATEST_FOLDER=$(python3 $SCRIPTS_PATH/classic-scrape-recursive.py $URL | grep -E "[0-9]" | grep '\.' | sed -e 's/v//g' -e 's!/!!' | sort -rV | head -1)
URL="${URL}v${LATEST_FOLDER}/src/"
LATEST_VERSION=$(python3 $SCRIPTS_PATH/classic-scrape-recursive.py $URL | grep tar |  grep $PACKAGE_PREFIX | sed 's/.*-//g' | sed 's/.[a-z].*//g' |  sed 's/\ /\n/g' | sed 's/[[:alpha:]]//g')
echo $LATEST_VERSION

