#!/bin/bash
source autobuild.conf
PACKAGE=$1

cd $BUILD_SCRIPTS_ROOT
REPO=spice/$1
PROJECT_ID=$(echo $REPO | sed 's!/!%2F!')
GITLAB_SERVER="https://gitlab.freedesktop.org"
LATEST_VER=$(curl \
  -Ls "$GITLAB_SERVER/api/v4/projects/$PROJECT_ID/releases/permalink/latest" |  jq -r '.tag_name' | sed  -e 's/^v//' -e 's/.*-//' )
echo $LATEST_VER
